/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ViralSearchRouteImport } from './routes/viral-search'
import { Route as UsuwanieDanychRouteImport } from './routes/usuwanie-danych'
import { Route as SeoRouteImport } from './routes/seo'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegulaminRouteImport } from './routes/regulamin'
import { Route as ProgramPartnerskiRouteImport } from './routes/program-partnerski'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PolitykaPrywatnosciRouteImport } from './routes/polityka-prywatnosci'
import { Route as LlmVisibilityRouteImport } from './routes/llm-visibility'
import { Route as LaunchRouteImport } from './routes/launch'
import { Route as KonkurencjaRouteImport } from './routes/konkurencja'
import { Route as KoloWzrostuRouteImport } from './routes/kolo-wzrostu'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CampaignComposerRouteImport } from './routes/campaign-composer'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as BezpieczenstwoRouteImport } from './routes/bezpieczenstwo'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LaunchIndexRouteImport } from './routes/launch.index'
import { Route as IntegrationsIndexRouteImport } from './routes/integrations.index'
import { Route as CampaignComposerIndexRouteImport } from './routes/campaign-composer.index'
import { Route as AgentIndexRouteImport } from './routes/agent.index'
import { Route as ProductsTeamRouteImport } from './routes/products.team'
import { Route as ProductsLibraryRouteImport } from './routes/products.library'
import { Route as ProductsChooseRouteImport } from './routes/products.choose'
import { Route as ProductsBrandVisualRouteImport } from './routes/products.brand-visual'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as CampaignComposerMediaRouteImport } from './routes/campaign-composer.media'
import { Route as CampaignComposerErrorsRouteImport } from './routes/campaign-composer.errors'
import { Route as CampaignComposerCollectionsRouteImport } from './routes/campaign-composer.collections'
import { Route as AssetsVideoRouteImport } from './routes/assets.video'
import { Route as AssetsGenerationsRouteImport } from './routes/assets.generations'
import { Route as AssetsGalleryRouteImport } from './routes/assets.gallery'
import { Route as AssetsEditorRouteImport } from './routes/assets.editor'
import { Route as AssetsCopyRouteImport } from './routes/assets.copy'
import { Route as AssetsAudioRouteImport } from './routes/assets.audio'
import { Route as AgentSkillsRouteImport } from './routes/agent.skills'
import { Route as AgentCustomizeRouteImport } from './routes/agent.customize'
import { Route as CampaignComposerDraftDraftIdRouteImport } from './routes/campaign-composer.draft.$draftId'
import { Route as CampaignComposerCampaignDraftIdRouteImport } from './routes/campaign-composer.campaign.$draftId'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableCampaignComposerQueueProcessRouteImport } from './routes/lovable/campaign-composer/queue/process'
import { Route as ApiPublicTiktokStartRouteImport } from './routes/api/public/tiktok.start'
import { Route as ApiPublicTiktokCallbackRouteImport } from './routes/api/public/tiktok.callback'
import { Route as ApiPublicOauthConfigRouteImport } from './routes/api/public/oauth.config'
import { Route as ApiPublicMicrosoftStartRouteImport } from './routes/api/public/microsoft.start'
import { Route as ApiPublicMicrosoftCallbackRouteImport } from './routes/api/public/microsoft.callback'
import { Route as ApiPublicMetaStartRouteImport } from './routes/api/public/meta.start'
import { Route as ApiPublicMetaCallbackRouteImport } from './routes/api/public/meta.callback'
import { Route as ApiPublicLinkedinStartRouteImport } from './routes/api/public/linkedin.start'
import { Route as ApiPublicLinkedinDisconnectRouteImport } from './routes/api/public/linkedin.disconnect'
import { Route as ApiPublicLinkedinCallbackRouteImport } from './routes/api/public/linkedin.callback'
import { Route as ApiPublicGoogleStartRouteImport } from './routes/api/public/google.start'
import { Route as ApiPublicGoogleDebugEnvRouteImport } from './routes/api/public/google.debug-env'
import { Route as ApiPublicGoogleCallbackRouteImport } from './routes/api/public/google.callback'
import { Route as ApiPublicAuthGoogleStatusRouteImport } from './routes/api/public/auth/google/status'
import { Route as ApiPublicAuthGoogleStartRouteImport } from './routes/api/public/auth/google/start'
import { Route as ApiPublicAuthGoogleCallbackRouteImport } from './routes/api/public/auth/google/callback'

const ViralSearchRoute = ViralSearchRouteImport.update({
  id: '/viral-search',
  path: '/viral-search',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuwanieDanychRoute = UsuwanieDanychRouteImport.update({
  id: '/usuwanie-danych',
  path: '/usuwanie-danych',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoRoute = SeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulaminRoute = RegulaminRouteImport.update({
  id: '/regulamin',
  path: '/regulamin',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramPartnerskiRoute = ProgramPartnerskiRouteImport.update({
  id: '/program-partnerski',
  path: '/program-partnerski',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitykaPrywatnosciRoute = PolitykaPrywatnosciRouteImport.update({
  id: '/polityka-prywatnosci',
  path: '/polityka-prywatnosci',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmVisibilityRoute = LlmVisibilityRouteImport.update({
  id: '/llm-visibility',
  path: '/llm-visibility',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchRoute = LaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const KonkurencjaRoute = KonkurencjaRouteImport.update({
  id: '/konkurencja',
  path: '/konkurencja',
  getParentRoute: () => rootRouteImport,
} as any)
const KoloWzrostuRoute = KoloWzrostuRouteImport.update({
  id: '/kolo-wzrostu',
  path: '/kolo-wzrostu',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignComposerRoute = CampaignComposerRouteImport.update({
  id: '/campaign-composer',
  path: '/campaign-composer',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const BezpieczenstwoRoute = BezpieczenstwoRouteImport.update({
  id: '/bezpieczenstwo',
  path: '/bezpieczenstwo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchIndexRoute = LaunchIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LaunchRoute,
} as any)
const IntegrationsIndexRoute = IntegrationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IntegrationsRoute,
} as any)
const CampaignComposerIndexRoute = CampaignComposerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CampaignComposerRoute,
} as any)
const AgentIndexRoute = AgentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentRoute,
} as any)
const ProductsTeamRoute = ProductsTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsLibraryRoute = ProductsLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsChooseRoute = ProductsChooseRouteImport.update({
  id: '/choose',
  path: '/choose',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsBrandVisualRoute = ProductsBrandVisualRouteImport.update({
  id: '/brand-visual',
  path: '/brand-visual',
  getParentRoute: () => ProductsRoute,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => CheckoutRoute,
} as any)
const CampaignComposerMediaRoute = CampaignComposerMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => CampaignComposerRoute,
} as any)
const CampaignComposerErrorsRoute = CampaignComposerErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => CampaignComposerRoute,
} as any)
const CampaignComposerCollectionsRoute =
  CampaignComposerCollectionsRouteImport.update({
    id: '/collections',
    path: '/collections',
    getParentRoute: () => CampaignComposerRoute,
  } as any)
const AssetsVideoRoute = AssetsVideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => AssetsRoute,
} as any)
const AssetsGenerationsRoute = AssetsGenerationsRouteImport.update({
  id: '/generations',
  path: '/generations',
  getParentRoute: () => AssetsRoute,
} as any)
const AssetsGalleryRoute = AssetsGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AssetsRoute,
} as any)
const AssetsEditorRoute = AssetsEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => AssetsRoute,
} as any)
const AssetsCopyRoute = AssetsCopyRouteImport.update({
  id: '/copy',
  path: '/copy',
  getParentRoute: () => AssetsRoute,
} as any)
const AssetsAudioRoute = AssetsAudioRouteImport.update({
  id: '/audio',
  path: '/audio',
  getParentRoute: () => AssetsRoute,
} as any)
const AgentSkillsRoute = AgentSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AgentRoute,
} as any)
const AgentCustomizeRoute = AgentCustomizeRouteImport.update({
  id: '/customize',
  path: '/customize',
  getParentRoute: () => AgentRoute,
} as any)
const CampaignComposerDraftDraftIdRoute =
  CampaignComposerDraftDraftIdRouteImport.update({
    id: '/draft/$draftId',
    path: '/draft/$draftId',
    getParentRoute: () => CampaignComposerRoute,
  } as any)
const CampaignComposerCampaignDraftIdRoute =
  CampaignComposerCampaignDraftIdRouteImport.update({
    id: '/campaign/$draftId',
    path: '/campaign/$draftId',
    getParentRoute: () => CampaignComposerRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableCampaignComposerQueueProcessRoute =
  LovableCampaignComposerQueueProcessRouteImport.update({
    id: '/lovable/campaign-composer/queue/process',
    path: '/lovable/campaign-composer/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTiktokStartRoute = ApiPublicTiktokStartRouteImport.update({
  id: '/api/public/tiktok/start',
  path: '/api/public/tiktok/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTiktokCallbackRoute = ApiPublicTiktokCallbackRouteImport.update({
  id: '/api/public/tiktok/callback',
  path: '/api/public/tiktok/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOauthConfigRoute = ApiPublicOauthConfigRouteImport.update({
  id: '/api/public/oauth/config',
  path: '/api/public/oauth/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMicrosoftStartRoute = ApiPublicMicrosoftStartRouteImport.update({
  id: '/api/public/microsoft/start',
  path: '/api/public/microsoft/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMicrosoftCallbackRoute =
  ApiPublicMicrosoftCallbackRouteImport.update({
    id: '/api/public/microsoft/callback',
    path: '/api/public/microsoft/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMetaStartRoute = ApiPublicMetaStartRouteImport.update({
  id: '/api/public/meta/start',
  path: '/api/public/meta/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMetaCallbackRoute = ApiPublicMetaCallbackRouteImport.update({
  id: '/api/public/meta/callback',
  path: '/api/public/meta/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLinkedinStartRoute = ApiPublicLinkedinStartRouteImport.update({
  id: '/api/public/linkedin/start',
  path: '/api/public/linkedin/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLinkedinDisconnectRoute =
  ApiPublicLinkedinDisconnectRouteImport.update({
    id: '/api/public/linkedin/disconnect',
    path: '/api/public/linkedin/disconnect',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLinkedinCallbackRoute =
  ApiPublicLinkedinCallbackRouteImport.update({
    id: '/api/public/linkedin/callback',
    path: '/api/public/linkedin/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGoogleStartRoute = ApiPublicGoogleStartRouteImport.update({
  id: '/api/public/google/start',
  path: '/api/public/google/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGoogleDebugEnvRoute = ApiPublicGoogleDebugEnvRouteImport.update({
  id: '/api/public/google/debug-env',
  path: '/api/public/google/debug-env',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGoogleCallbackRoute = ApiPublicGoogleCallbackRouteImport.update({
  id: '/api/public/google/callback',
  path: '/api/public/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthGoogleStatusRoute =
  ApiPublicAuthGoogleStatusRouteImport.update({
    id: '/api/public/auth/google/status',
    path: '/api/public/auth/google/status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAuthGoogleStartRoute =
  ApiPublicAuthGoogleStartRouteImport.update({
    id: '/api/public/auth/google/start',
    path: '/api/public/auth/google/start',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAuthGoogleCallbackRoute =
  ApiPublicAuthGoogleCallbackRouteImport.update({
    id: '/api/public/auth/google/callback',
    path: '/api/public/auth/google/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof AgentRouteWithChildren
  '/assets': typeof AssetsRouteWithChildren
  '/auth': typeof AuthRoute
  '/bezpieczenstwo': typeof BezpieczenstwoRoute
  '/billing': typeof BillingRoute
  '/campaign-composer': typeof CampaignComposerRouteWithChildren
  '/checkout': typeof CheckoutRouteWithChildren
  '/integrations': typeof IntegrationsRouteWithChildren
  '/kolo-wzrostu': typeof KoloWzrostuRoute
  '/konkurencja': typeof KonkurencjaRoute
  '/launch': typeof LaunchRouteWithChildren
  '/llm-visibility': typeof LlmVisibilityRoute
  '/polityka-prywatnosci': typeof PolitykaPrywatnosciRoute
  '/products': typeof ProductsRouteWithChildren
  '/program-partnerski': typeof ProgramPartnerskiRoute
  '/regulamin': typeof RegulaminRoute
  '/reset-password': typeof ResetPasswordRoute
  '/seo': typeof SeoRoute
  '/usuwanie-danych': typeof UsuwanieDanychRoute
  '/viral-search': typeof ViralSearchRoute
  '/agent/customize': typeof AgentCustomizeRoute
  '/agent/skills': typeof AgentSkillsRoute
  '/assets/audio': typeof AssetsAudioRoute
  '/assets/copy': typeof AssetsCopyRoute
  '/assets/editor': typeof AssetsEditorRoute
  '/assets/gallery': typeof AssetsGalleryRoute
  '/assets/generations': typeof AssetsGenerationsRoute
  '/assets/video': typeof AssetsVideoRoute
  '/campaign-composer/collections': typeof CampaignComposerCollectionsRoute
  '/campaign-composer/errors': typeof CampaignComposerErrorsRoute
  '/campaign-composer/media': typeof CampaignComposerMediaRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/products/brand-visual': typeof ProductsBrandVisualRoute
  '/products/choose': typeof ProductsChooseRoute
  '/products/library': typeof ProductsLibraryRoute
  '/products/team': typeof ProductsTeamRoute
  '/agent/': typeof AgentIndexRoute
  '/campaign-composer/': typeof CampaignComposerIndexRoute
  '/integrations/': typeof IntegrationsIndexRoute
  '/launch/': typeof LaunchIndexRoute
  '/campaign-composer/campaign/$draftId': typeof CampaignComposerCampaignDraftIdRoute
  '/campaign-composer/draft/$draftId': typeof CampaignComposerDraftDraftIdRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
  '/api/public/google/debug-env': typeof ApiPublicGoogleDebugEnvRoute
  '/api/public/google/start': typeof ApiPublicGoogleStartRoute
  '/api/public/linkedin/callback': typeof ApiPublicLinkedinCallbackRoute
  '/api/public/linkedin/disconnect': typeof ApiPublicLinkedinDisconnectRoute
  '/api/public/linkedin/start': typeof ApiPublicLinkedinStartRoute
  '/api/public/meta/callback': typeof ApiPublicMetaCallbackRoute
  '/api/public/meta/start': typeof ApiPublicMetaStartRoute
  '/api/public/microsoft/callback': typeof ApiPublicMicrosoftCallbackRoute
  '/api/public/microsoft/start': typeof ApiPublicMicrosoftStartRoute
  '/api/public/oauth/config': typeof ApiPublicOauthConfigRoute
  '/api/public/tiktok/callback': typeof ApiPublicTiktokCallbackRoute
  '/api/public/tiktok/start': typeof ApiPublicTiktokStartRoute
  '/lovable/campaign-composer/queue/process': typeof LovableCampaignComposerQueueProcessRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/api/public/auth/google/callback': typeof ApiPublicAuthGoogleCallbackRoute
  '/api/public/auth/google/start': typeof ApiPublicAuthGoogleStartRoute
  '/api/public/auth/google/status': typeof ApiPublicAuthGoogleStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRouteWithChildren
  '/auth': typeof AuthRoute
  '/bezpieczenstwo': typeof BezpieczenstwoRoute
  '/billing': typeof BillingRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/kolo-wzrostu': typeof KoloWzrostuRoute
  '/konkurencja': typeof KonkurencjaRoute
  '/llm-visibility': typeof LlmVisibilityRoute
  '/polityka-prywatnosci': typeof PolitykaPrywatnosciRoute
  '/products': typeof ProductsRouteWithChildren
  '/program-partnerski': typeof ProgramPartnerskiRoute
  '/regulamin': typeof RegulaminRoute
  '/reset-password': typeof ResetPasswordRoute
  '/seo': typeof SeoRoute
  '/usuwanie-danych': typeof UsuwanieDanychRoute
  '/viral-search': typeof ViralSearchRoute
  '/agent/customize': typeof AgentCustomizeRoute
  '/agent/skills': typeof AgentSkillsRoute
  '/assets/audio': typeof AssetsAudioRoute
  '/assets/copy': typeof AssetsCopyRoute
  '/assets/editor': typeof AssetsEditorRoute
  '/assets/gallery': typeof AssetsGalleryRoute
  '/assets/generations': typeof AssetsGenerationsRoute
  '/assets/video': typeof AssetsVideoRoute
  '/campaign-composer/collections': typeof CampaignComposerCollectionsRoute
  '/campaign-composer/errors': typeof CampaignComposerErrorsRoute
  '/campaign-composer/media': typeof CampaignComposerMediaRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/products/brand-visual': typeof ProductsBrandVisualRoute
  '/products/choose': typeof ProductsChooseRoute
  '/products/library': typeof ProductsLibraryRoute
  '/products/team': typeof ProductsTeamRoute
  '/agent': typeof AgentIndexRoute
  '/campaign-composer': typeof CampaignComposerIndexRoute
  '/integrations': typeof IntegrationsIndexRoute
  '/launch': typeof LaunchIndexRoute
  '/campaign-composer/campaign/$draftId': typeof CampaignComposerCampaignDraftIdRoute
  '/campaign-composer/draft/$draftId': typeof CampaignComposerDraftDraftIdRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
  '/api/public/google/debug-env': typeof ApiPublicGoogleDebugEnvRoute
  '/api/public/google/start': typeof ApiPublicGoogleStartRoute
  '/api/public/linkedin/callback': typeof ApiPublicLinkedinCallbackRoute
  '/api/public/linkedin/disconnect': typeof ApiPublicLinkedinDisconnectRoute
  '/api/public/linkedin/start': typeof ApiPublicLinkedinStartRoute
  '/api/public/meta/callback': typeof ApiPublicMetaCallbackRoute
  '/api/public/meta/start': typeof ApiPublicMetaStartRoute
  '/api/public/microsoft/callback': typeof ApiPublicMicrosoftCallbackRoute
  '/api/public/microsoft/start': typeof ApiPublicMicrosoftStartRoute
  '/api/public/oauth/config': typeof ApiPublicOauthConfigRoute
  '/api/public/tiktok/callback': typeof ApiPublicTiktokCallbackRoute
  '/api/public/tiktok/start': typeof ApiPublicTiktokStartRoute
  '/lovable/campaign-composer/queue/process': typeof LovableCampaignComposerQueueProcessRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/api/public/auth/google/callback': typeof ApiPublicAuthGoogleCallbackRoute
  '/api/public/auth/google/start': typeof ApiPublicAuthGoogleStartRoute
  '/api/public/auth/google/status': typeof ApiPublicAuthGoogleStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent': typeof AgentRouteWithChildren
  '/assets': typeof AssetsRouteWithChildren
  '/auth': typeof AuthRoute
  '/bezpieczenstwo': typeof BezpieczenstwoRoute
  '/billing': typeof BillingRoute
  '/campaign-composer': typeof CampaignComposerRouteWithChildren
  '/checkout': typeof CheckoutRouteWithChildren
  '/integrations': typeof IntegrationsRouteWithChildren
  '/kolo-wzrostu': typeof KoloWzrostuRoute
  '/konkurencja': typeof KonkurencjaRoute
  '/launch': typeof LaunchRouteWithChildren
  '/llm-visibility': typeof LlmVisibilityRoute
  '/polityka-prywatnosci': typeof PolitykaPrywatnosciRoute
  '/products': typeof ProductsRouteWithChildren
  '/program-partnerski': typeof ProgramPartnerskiRoute
  '/regulamin': typeof RegulaminRoute
  '/reset-password': typeof ResetPasswordRoute
  '/seo': typeof SeoRoute
  '/usuwanie-danych': typeof UsuwanieDanychRoute
  '/viral-search': typeof ViralSearchRoute
  '/agent/customize': typeof AgentCustomizeRoute
  '/agent/skills': typeof AgentSkillsRoute
  '/assets/audio': typeof AssetsAudioRoute
  '/assets/copy': typeof AssetsCopyRoute
  '/assets/editor': typeof AssetsEditorRoute
  '/assets/gallery': typeof AssetsGalleryRoute
  '/assets/generations': typeof AssetsGenerationsRoute
  '/assets/video': typeof AssetsVideoRoute
  '/campaign-composer/collections': typeof CampaignComposerCollectionsRoute
  '/campaign-composer/errors': typeof CampaignComposerErrorsRoute
  '/campaign-composer/media': typeof CampaignComposerMediaRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/products/brand-visual': typeof ProductsBrandVisualRoute
  '/products/choose': typeof ProductsChooseRoute
  '/products/library': typeof ProductsLibraryRoute
  '/products/team': typeof ProductsTeamRoute
  '/agent/': typeof AgentIndexRoute
  '/campaign-composer/': typeof CampaignComposerIndexRoute
  '/integrations/': typeof IntegrationsIndexRoute
  '/launch/': typeof LaunchIndexRoute
  '/campaign-composer/campaign/$draftId': typeof CampaignComposerCampaignDraftIdRoute
  '/campaign-composer/draft/$draftId': typeof CampaignComposerDraftDraftIdRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
  '/api/public/google/debug-env': typeof ApiPublicGoogleDebugEnvRoute
  '/api/public/google/start': typeof ApiPublicGoogleStartRoute
  '/api/public/linkedin/callback': typeof ApiPublicLinkedinCallbackRoute
  '/api/public/linkedin/disconnect': typeof ApiPublicLinkedinDisconnectRoute
  '/api/public/linkedin/start': typeof ApiPublicLinkedinStartRoute
  '/api/public/meta/callback': typeof ApiPublicMetaCallbackRoute
  '/api/public/meta/start': typeof ApiPublicMetaStartRoute
  '/api/public/microsoft/callback': typeof ApiPublicMicrosoftCallbackRoute
  '/api/public/microsoft/start': typeof ApiPublicMicrosoftStartRoute
  '/api/public/oauth/config': typeof ApiPublicOauthConfigRoute
  '/api/public/tiktok/callback': typeof ApiPublicTiktokCallbackRoute
  '/api/public/tiktok/start': typeof ApiPublicTiktokStartRoute
  '/lovable/campaign-composer/queue/process': typeof LovableCampaignComposerQueueProcessRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/api/public/auth/google/callback': typeof ApiPublicAuthGoogleCallbackRoute
  '/api/public/auth/google/start': typeof ApiPublicAuthGoogleStartRoute
  '/api/public/auth/google/status': typeof ApiPublicAuthGoogleStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent'
    | '/assets'
    | '/auth'
    | '/bezpieczenstwo'
    | '/billing'
    | '/campaign-composer'
    | '/checkout'
    | '/integrations'
    | '/kolo-wzrostu'
    | '/konkurencja'
    | '/launch'
    | '/llm-visibility'
    | '/polityka-prywatnosci'
    | '/products'
    | '/program-partnerski'
    | '/regulamin'
    | '/reset-password'
    | '/seo'
    | '/usuwanie-danych'
    | '/viral-search'
    | '/agent/customize'
    | '/agent/skills'
    | '/assets/audio'
    | '/assets/copy'
    | '/assets/editor'
    | '/assets/gallery'
    | '/assets/generations'
    | '/assets/video'
    | '/campaign-composer/collections'
    | '/campaign-composer/errors'
    | '/campaign-composer/media'
    | '/checkout/return'
    | '/products/brand-visual'
    | '/products/choose'
    | '/products/library'
    | '/products/team'
    | '/agent/'
    | '/campaign-composer/'
    | '/integrations/'
    | '/launch/'
    | '/campaign-composer/campaign/$draftId'
    | '/campaign-composer/draft/$draftId'
    | '/api/public/google/callback'
    | '/api/public/google/debug-env'
    | '/api/public/google/start'
    | '/api/public/linkedin/callback'
    | '/api/public/linkedin/disconnect'
    | '/api/public/linkedin/start'
    | '/api/public/meta/callback'
    | '/api/public/meta/start'
    | '/api/public/microsoft/callback'
    | '/api/public/microsoft/start'
    | '/api/public/oauth/config'
    | '/api/public/tiktok/callback'
    | '/api/public/tiktok/start'
    | '/lovable/campaign-composer/queue/process'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/api/public/auth/google/callback'
    | '/api/public/auth/google/start'
    | '/api/public/auth/google/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assets'
    | '/auth'
    | '/bezpieczenstwo'
    | '/billing'
    | '/checkout'
    | '/kolo-wzrostu'
    | '/konkurencja'
    | '/llm-visibility'
    | '/polityka-prywatnosci'
    | '/products'
    | '/program-partnerski'
    | '/regulamin'
    | '/reset-password'
    | '/seo'
    | '/usuwanie-danych'
    | '/viral-search'
    | '/agent/customize'
    | '/agent/skills'
    | '/assets/audio'
    | '/assets/copy'
    | '/assets/editor'
    | '/assets/gallery'
    | '/assets/generations'
    | '/assets/video'
    | '/campaign-composer/collections'
    | '/campaign-composer/errors'
    | '/campaign-composer/media'
    | '/checkout/return'
    | '/products/brand-visual'
    | '/products/choose'
    | '/products/library'
    | '/products/team'
    | '/agent'
    | '/campaign-composer'
    | '/integrations'
    | '/launch'
    | '/campaign-composer/campaign/$draftId'
    | '/campaign-composer/draft/$draftId'
    | '/api/public/google/callback'
    | '/api/public/google/debug-env'
    | '/api/public/google/start'
    | '/api/public/linkedin/callback'
    | '/api/public/linkedin/disconnect'
    | '/api/public/linkedin/start'
    | '/api/public/meta/callback'
    | '/api/public/meta/start'
    | '/api/public/microsoft/callback'
    | '/api/public/microsoft/start'
    | '/api/public/oauth/config'
    | '/api/public/tiktok/callback'
    | '/api/public/tiktok/start'
    | '/lovable/campaign-composer/queue/process'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/api/public/auth/google/callback'
    | '/api/public/auth/google/start'
    | '/api/public/auth/google/status'
  id:
    | '__root__'
    | '/'
    | '/agent'
    | '/assets'
    | '/auth'
    | '/bezpieczenstwo'
    | '/billing'
    | '/campaign-composer'
    | '/checkout'
    | '/integrations'
    | '/kolo-wzrostu'
    | '/konkurencja'
    | '/launch'
    | '/llm-visibility'
    | '/polityka-prywatnosci'
    | '/products'
    | '/program-partnerski'
    | '/regulamin'
    | '/reset-password'
    | '/seo'
    | '/usuwanie-danych'
    | '/viral-search'
    | '/agent/customize'
    | '/agent/skills'
    | '/assets/audio'
    | '/assets/copy'
    | '/assets/editor'
    | '/assets/gallery'
    | '/assets/generations'
    | '/assets/video'
    | '/campaign-composer/collections'
    | '/campaign-composer/errors'
    | '/campaign-composer/media'
    | '/checkout/return'
    | '/products/brand-visual'
    | '/products/choose'
    | '/products/library'
    | '/products/team'
    | '/agent/'
    | '/campaign-composer/'
    | '/integrations/'
    | '/launch/'
    | '/campaign-composer/campaign/$draftId'
    | '/campaign-composer/draft/$draftId'
    | '/api/public/google/callback'
    | '/api/public/google/debug-env'
    | '/api/public/google/start'
    | '/api/public/linkedin/callback'
    | '/api/public/linkedin/disconnect'
    | '/api/public/linkedin/start'
    | '/api/public/meta/callback'
    | '/api/public/meta/start'
    | '/api/public/microsoft/callback'
    | '/api/public/microsoft/start'
    | '/api/public/oauth/config'
    | '/api/public/tiktok/callback'
    | '/api/public/tiktok/start'
    | '/lovable/campaign-composer/queue/process'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/api/public/auth/google/callback'
    | '/api/public/auth/google/start'
    | '/api/public/auth/google/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRoute: typeof AgentRouteWithChildren
  AssetsRoute: typeof AssetsRouteWithChildren
  AuthRoute: typeof AuthRoute
  BezpieczenstwoRoute: typeof BezpieczenstwoRoute
  BillingRoute: typeof BillingRoute
  CampaignComposerRoute: typeof CampaignComposerRouteWithChildren
  CheckoutRoute: typeof CheckoutRouteWithChildren
  IntegrationsRoute: typeof IntegrationsRouteWithChildren
  KoloWzrostuRoute: typeof KoloWzrostuRoute
  KonkurencjaRoute: typeof KonkurencjaRoute
  LaunchRoute: typeof LaunchRouteWithChildren
  LlmVisibilityRoute: typeof LlmVisibilityRoute
  PolitykaPrywatnosciRoute: typeof PolitykaPrywatnosciRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  ProgramPartnerskiRoute: typeof ProgramPartnerskiRoute
  RegulaminRoute: typeof RegulaminRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SeoRoute: typeof SeoRoute
  UsuwanieDanychRoute: typeof UsuwanieDanychRoute
  ViralSearchRoute: typeof ViralSearchRoute
  ApiPublicGoogleCallbackRoute: typeof ApiPublicGoogleCallbackRoute
  ApiPublicGoogleDebugEnvRoute: typeof ApiPublicGoogleDebugEnvRoute
  ApiPublicGoogleStartRoute: typeof ApiPublicGoogleStartRoute
  ApiPublicLinkedinCallbackRoute: typeof ApiPublicLinkedinCallbackRoute
  ApiPublicLinkedinDisconnectRoute: typeof ApiPublicLinkedinDisconnectRoute
  ApiPublicLinkedinStartRoute: typeof ApiPublicLinkedinStartRoute
  ApiPublicMetaCallbackRoute: typeof ApiPublicMetaCallbackRoute
  ApiPublicMetaStartRoute: typeof ApiPublicMetaStartRoute
  ApiPublicMicrosoftCallbackRoute: typeof ApiPublicMicrosoftCallbackRoute
  ApiPublicMicrosoftStartRoute: typeof ApiPublicMicrosoftStartRoute
  ApiPublicOauthConfigRoute: typeof ApiPublicOauthConfigRoute
  ApiPublicTiktokCallbackRoute: typeof ApiPublicTiktokCallbackRoute
  ApiPublicTiktokStartRoute: typeof ApiPublicTiktokStartRoute
  LovableCampaignComposerQueueProcessRoute: typeof LovableCampaignComposerQueueProcessRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  ApiPublicAuthGoogleCallbackRoute: typeof ApiPublicAuthGoogleCallbackRoute
  ApiPublicAuthGoogleStartRoute: typeof ApiPublicAuthGoogleStartRoute
  ApiPublicAuthGoogleStatusRoute: typeof ApiPublicAuthGoogleStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/viral-search': {
      id: '/viral-search'
      path: '/viral-search'
      fullPath: '/viral-search'
      preLoaderRoute: typeof ViralSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuwanie-danych': {
      id: '/usuwanie-danych'
      path: '/usuwanie-danych'
      fullPath: '/usuwanie-danych'
      preLoaderRoute: typeof UsuwanieDanychRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo': {
      id: '/seo'
      path: '/seo'
      fullPath: '/seo'
      preLoaderRoute: typeof SeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulamin': {
      id: '/regulamin'
      path: '/regulamin'
      fullPath: '/regulamin'
      preLoaderRoute: typeof RegulaminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program-partnerski': {
      id: '/program-partnerski'
      path: '/program-partnerski'
      fullPath: '/program-partnerski'
      preLoaderRoute: typeof ProgramPartnerskiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polityka-prywatnosci': {
      id: '/polityka-prywatnosci'
      path: '/polityka-prywatnosci'
      fullPath: '/polityka-prywatnosci'
      preLoaderRoute: typeof PolitykaPrywatnosciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llm-visibility': {
      id: '/llm-visibility'
      path: '/llm-visibility'
      fullPath: '/llm-visibility'
      preLoaderRoute: typeof LlmVisibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch': {
      id: '/launch'
      path: '/launch'
      fullPath: '/launch'
      preLoaderRoute: typeof LaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konkurencja': {
      id: '/konkurencja'
      path: '/konkurencja'
      fullPath: '/konkurencja'
      preLoaderRoute: typeof KonkurencjaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kolo-wzrostu': {
      id: '/kolo-wzrostu'
      path: '/kolo-wzrostu'
      fullPath: '/kolo-wzrostu'
      preLoaderRoute: typeof KoloWzrostuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign-composer': {
      id: '/campaign-composer'
      path: '/campaign-composer'
      fullPath: '/campaign-composer'
      preLoaderRoute: typeof CampaignComposerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bezpieczenstwo': {
      id: '/bezpieczenstwo'
      path: '/bezpieczenstwo'
      fullPath: '/bezpieczenstwo'
      preLoaderRoute: typeof BezpieczenstwoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch/': {
      id: '/launch/'
      path: '/'
      fullPath: '/launch/'
      preLoaderRoute: typeof LaunchIndexRouteImport
      parentRoute: typeof LaunchRoute
    }
    '/integrations/': {
      id: '/integrations/'
      path: '/'
      fullPath: '/integrations/'
      preLoaderRoute: typeof IntegrationsIndexRouteImport
      parentRoute: typeof IntegrationsRoute
    }
    '/campaign-composer/': {
      id: '/campaign-composer/'
      path: '/'
      fullPath: '/campaign-composer/'
      preLoaderRoute: typeof CampaignComposerIndexRouteImport
      parentRoute: typeof CampaignComposerRoute
    }
    '/agent/': {
      id: '/agent/'
      path: '/'
      fullPath: '/agent/'
      preLoaderRoute: typeof AgentIndexRouteImport
      parentRoute: typeof AgentRoute
    }
    '/products/team': {
      id: '/products/team'
      path: '/team'
      fullPath: '/products/team'
      preLoaderRoute: typeof ProductsTeamRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/library': {
      id: '/products/library'
      path: '/library'
      fullPath: '/products/library'
      preLoaderRoute: typeof ProductsLibraryRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/choose': {
      id: '/products/choose'
      path: '/choose'
      fullPath: '/products/choose'
      preLoaderRoute: typeof ProductsChooseRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/brand-visual': {
      id: '/products/brand-visual'
      path: '/brand-visual'
      fullPath: '/products/brand-visual'
      preLoaderRoute: typeof ProductsBrandVisualRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/campaign-composer/media': {
      id: '/campaign-composer/media'
      path: '/media'
      fullPath: '/campaign-composer/media'
      preLoaderRoute: typeof CampaignComposerMediaRouteImport
      parentRoute: typeof CampaignComposerRoute
    }
    '/campaign-composer/errors': {
      id: '/campaign-composer/errors'
      path: '/errors'
      fullPath: '/campaign-composer/errors'
      preLoaderRoute: typeof CampaignComposerErrorsRouteImport
      parentRoute: typeof CampaignComposerRoute
    }
    '/campaign-composer/collections': {
      id: '/campaign-composer/collections'
      path: '/collections'
      fullPath: '/campaign-composer/collections'
      preLoaderRoute: typeof CampaignComposerCollectionsRouteImport
      parentRoute: typeof CampaignComposerRoute
    }
    '/assets/video': {
      id: '/assets/video'
      path: '/video'
      fullPath: '/assets/video'
      preLoaderRoute: typeof AssetsVideoRouteImport
      parentRoute: typeof AssetsRoute
    }
    '/assets/generations': {
      id: '/assets/generations'
      path: '/generations'
      fullPath: '/assets/generations'
      preLoaderRoute: typeof AssetsGenerationsRouteImport
      parentRoute: typeof AssetsRoute
    }
    '/assets/gallery': {
      id: '/assets/gallery'
      path: '/gallery'
      fullPath: '/assets/gallery'
      preLoaderRoute: typeof AssetsGalleryRouteImport
      parentRoute: typeof AssetsRoute
    }
    '/assets/editor': {
      id: '/assets/editor'
      path: '/editor'
      fullPath: '/assets/editor'
      preLoaderRoute: typeof AssetsEditorRouteImport
      parentRoute: typeof AssetsRoute
    }
    '/assets/copy': {
      id: '/assets/copy'
      path: '/copy'
      fullPath: '/assets/copy'
      preLoaderRoute: typeof AssetsCopyRouteImport
      parentRoute: typeof AssetsRoute
    }
    '/assets/audio': {
      id: '/assets/audio'
      path: '/audio'
      fullPath: '/assets/audio'
      preLoaderRoute: typeof AssetsAudioRouteImport
      parentRoute: typeof AssetsRoute
    }
    '/agent/skills': {
      id: '/agent/skills'
      path: '/skills'
      fullPath: '/agent/skills'
      preLoaderRoute: typeof AgentSkillsRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/customize': {
      id: '/agent/customize'
      path: '/customize'
      fullPath: '/agent/customize'
      preLoaderRoute: typeof AgentCustomizeRouteImport
      parentRoute: typeof AgentRoute
    }
    '/campaign-composer/draft/$draftId': {
      id: '/campaign-composer/draft/$draftId'
      path: '/draft/$draftId'
      fullPath: '/campaign-composer/draft/$draftId'
      preLoaderRoute: typeof CampaignComposerDraftDraftIdRouteImport
      parentRoute: typeof CampaignComposerRoute
    }
    '/campaign-composer/campaign/$draftId': {
      id: '/campaign-composer/campaign/$draftId'
      path: '/campaign/$draftId'
      fullPath: '/campaign-composer/campaign/$draftId'
      preLoaderRoute: typeof CampaignComposerCampaignDraftIdRouteImport
      parentRoute: typeof CampaignComposerRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/campaign-composer/queue/process': {
      id: '/lovable/campaign-composer/queue/process'
      path: '/lovable/campaign-composer/queue/process'
      fullPath: '/lovable/campaign-composer/queue/process'
      preLoaderRoute: typeof LovableCampaignComposerQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tiktok/start': {
      id: '/api/public/tiktok/start'
      path: '/api/public/tiktok/start'
      fullPath: '/api/public/tiktok/start'
      preLoaderRoute: typeof ApiPublicTiktokStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tiktok/callback': {
      id: '/api/public/tiktok/callback'
      path: '/api/public/tiktok/callback'
      fullPath: '/api/public/tiktok/callback'
      preLoaderRoute: typeof ApiPublicTiktokCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/config': {
      id: '/api/public/oauth/config'
      path: '/api/public/oauth/config'
      fullPath: '/api/public/oauth/config'
      preLoaderRoute: typeof ApiPublicOauthConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/microsoft/start': {
      id: '/api/public/microsoft/start'
      path: '/api/public/microsoft/start'
      fullPath: '/api/public/microsoft/start'
      preLoaderRoute: typeof ApiPublicMicrosoftStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/microsoft/callback': {
      id: '/api/public/microsoft/callback'
      path: '/api/public/microsoft/callback'
      fullPath: '/api/public/microsoft/callback'
      preLoaderRoute: typeof ApiPublicMicrosoftCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/meta/start': {
      id: '/api/public/meta/start'
      path: '/api/public/meta/start'
      fullPath: '/api/public/meta/start'
      preLoaderRoute: typeof ApiPublicMetaStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/meta/callback': {
      id: '/api/public/meta/callback'
      path: '/api/public/meta/callback'
      fullPath: '/api/public/meta/callback'
      preLoaderRoute: typeof ApiPublicMetaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/linkedin/start': {
      id: '/api/public/linkedin/start'
      path: '/api/public/linkedin/start'
      fullPath: '/api/public/linkedin/start'
      preLoaderRoute: typeof ApiPublicLinkedinStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/linkedin/disconnect': {
      id: '/api/public/linkedin/disconnect'
      path: '/api/public/linkedin/disconnect'
      fullPath: '/api/public/linkedin/disconnect'
      preLoaderRoute: typeof ApiPublicLinkedinDisconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/linkedin/callback': {
      id: '/api/public/linkedin/callback'
      path: '/api/public/linkedin/callback'
      fullPath: '/api/public/linkedin/callback'
      preLoaderRoute: typeof ApiPublicLinkedinCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google/start': {
      id: '/api/public/google/start'
      path: '/api/public/google/start'
      fullPath: '/api/public/google/start'
      preLoaderRoute: typeof ApiPublicGoogleStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google/debug-env': {
      id: '/api/public/google/debug-env'
      path: '/api/public/google/debug-env'
      fullPath: '/api/public/google/debug-env'
      preLoaderRoute: typeof ApiPublicGoogleDebugEnvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google/callback': {
      id: '/api/public/google/callback'
      path: '/api/public/google/callback'
      fullPath: '/api/public/google/callback'
      preLoaderRoute: typeof ApiPublicGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/google/status': {
      id: '/api/public/auth/google/status'
      path: '/api/public/auth/google/status'
      fullPath: '/api/public/auth/google/status'
      preLoaderRoute: typeof ApiPublicAuthGoogleStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/google/start': {
      id: '/api/public/auth/google/start'
      path: '/api/public/auth/google/start'
      fullPath: '/api/public/auth/google/start'
      preLoaderRoute: typeof ApiPublicAuthGoogleStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/google/callback': {
      id: '/api/public/auth/google/callback'
      path: '/api/public/auth/google/callback'
      fullPath: '/api/public/auth/google/callback'
      preLoaderRoute: typeof ApiPublicAuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AgentRouteChildren {
  AgentCustomizeRoute: typeof AgentCustomizeRoute
  AgentSkillsRoute: typeof AgentSkillsRoute
  AgentIndexRoute: typeof AgentIndexRoute
}

const AgentRouteChildren: AgentRouteChildren = {
  AgentCustomizeRoute: AgentCustomizeRoute,
  AgentSkillsRoute: AgentSkillsRoute,
  AgentIndexRoute: AgentIndexRoute,
}

const AgentRouteWithChildren = AgentRoute._addFileChildren(AgentRouteChildren)

interface AssetsRouteChildren {
  AssetsAudioRoute: typeof AssetsAudioRoute
  AssetsCopyRoute: typeof AssetsCopyRoute
  AssetsEditorRoute: typeof AssetsEditorRoute
  AssetsGalleryRoute: typeof AssetsGalleryRoute
  AssetsGenerationsRoute: typeof AssetsGenerationsRoute
  AssetsVideoRoute: typeof AssetsVideoRoute
}

const AssetsRouteChildren: AssetsRouteChildren = {
  AssetsAudioRoute: AssetsAudioRoute,
  AssetsCopyRoute: AssetsCopyRoute,
  AssetsEditorRoute: AssetsEditorRoute,
  AssetsGalleryRoute: AssetsGalleryRoute,
  AssetsGenerationsRoute: AssetsGenerationsRoute,
  AssetsVideoRoute: AssetsVideoRoute,
}

const AssetsRouteWithChildren =
  AssetsRoute._addFileChildren(AssetsRouteChildren)

interface CampaignComposerRouteChildren {
  CampaignComposerCollectionsRoute: typeof CampaignComposerCollectionsRoute
  CampaignComposerErrorsRoute: typeof CampaignComposerErrorsRoute
  CampaignComposerMediaRoute: typeof CampaignComposerMediaRoute
  CampaignComposerIndexRoute: typeof CampaignComposerIndexRoute
  CampaignComposerCampaignDraftIdRoute: typeof CampaignComposerCampaignDraftIdRoute
  CampaignComposerDraftDraftIdRoute: typeof CampaignComposerDraftDraftIdRoute
}

const CampaignComposerRouteChildren: CampaignComposerRouteChildren = {
  CampaignComposerCollectionsRoute: CampaignComposerCollectionsRoute,
  CampaignComposerErrorsRoute: CampaignComposerErrorsRoute,
  CampaignComposerMediaRoute: CampaignComposerMediaRoute,
  CampaignComposerIndexRoute: CampaignComposerIndexRoute,
  CampaignComposerCampaignDraftIdRoute: CampaignComposerCampaignDraftIdRoute,
  CampaignComposerDraftDraftIdRoute: CampaignComposerDraftDraftIdRoute,
}

const CampaignComposerRouteWithChildren =
  CampaignComposerRoute._addFileChildren(CampaignComposerRouteChildren)

interface CheckoutRouteChildren {
  CheckoutReturnRoute: typeof CheckoutReturnRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutReturnRoute: CheckoutReturnRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

interface IntegrationsRouteChildren {
  IntegrationsIndexRoute: typeof IntegrationsIndexRoute
}

const IntegrationsRouteChildren: IntegrationsRouteChildren = {
  IntegrationsIndexRoute: IntegrationsIndexRoute,
}

const IntegrationsRouteWithChildren = IntegrationsRoute._addFileChildren(
  IntegrationsRouteChildren,
)

interface LaunchRouteChildren {
  LaunchIndexRoute: typeof LaunchIndexRoute
}

const LaunchRouteChildren: LaunchRouteChildren = {
  LaunchIndexRoute: LaunchIndexRoute,
}

const LaunchRouteWithChildren =
  LaunchRoute._addFileChildren(LaunchRouteChildren)

interface ProductsRouteChildren {
  ProductsBrandVisualRoute: typeof ProductsBrandVisualRoute
  ProductsChooseRoute: typeof ProductsChooseRoute
  ProductsLibraryRoute: typeof ProductsLibraryRoute
  ProductsTeamRoute: typeof ProductsTeamRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsBrandVisualRoute: ProductsBrandVisualRoute,
  ProductsChooseRoute: ProductsChooseRoute,
  ProductsLibraryRoute: ProductsLibraryRoute,
  ProductsTeamRoute: ProductsTeamRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRoute: AgentRouteWithChildren,
  AssetsRoute: AssetsRouteWithChildren,
  AuthRoute: AuthRoute,
  BezpieczenstwoRoute: BezpieczenstwoRoute,
  BillingRoute: BillingRoute,
  CampaignComposerRoute: CampaignComposerRouteWithChildren,
  CheckoutRoute: CheckoutRouteWithChildren,
  IntegrationsRoute: IntegrationsRouteWithChildren,
  KoloWzrostuRoute: KoloWzrostuRoute,
  KonkurencjaRoute: KonkurencjaRoute,
  LaunchRoute: LaunchRouteWithChildren,
  LlmVisibilityRoute: LlmVisibilityRoute,
  PolitykaPrywatnosciRoute: PolitykaPrywatnosciRoute,
  ProductsRoute: ProductsRouteWithChildren,
  ProgramPartnerskiRoute: ProgramPartnerskiRoute,
  RegulaminRoute: RegulaminRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SeoRoute: SeoRoute,
  UsuwanieDanychRoute: UsuwanieDanychRoute,
  ViralSearchRoute: ViralSearchRoute,
  ApiPublicGoogleCallbackRoute: ApiPublicGoogleCallbackRoute,
  ApiPublicGoogleDebugEnvRoute: ApiPublicGoogleDebugEnvRoute,
  ApiPublicGoogleStartRoute: ApiPublicGoogleStartRoute,
  ApiPublicLinkedinCallbackRoute: ApiPublicLinkedinCallbackRoute,
  ApiPublicLinkedinDisconnectRoute: ApiPublicLinkedinDisconnectRoute,
  ApiPublicLinkedinStartRoute: ApiPublicLinkedinStartRoute,
  ApiPublicMetaCallbackRoute: ApiPublicMetaCallbackRoute,
  ApiPublicMetaStartRoute: ApiPublicMetaStartRoute,
  ApiPublicMicrosoftCallbackRoute: ApiPublicMicrosoftCallbackRoute,
  ApiPublicMicrosoftStartRoute: ApiPublicMicrosoftStartRoute,
  ApiPublicOauthConfigRoute: ApiPublicOauthConfigRoute,
  ApiPublicTiktokCallbackRoute: ApiPublicTiktokCallbackRoute,
  ApiPublicTiktokStartRoute: ApiPublicTiktokStartRoute,
  LovableCampaignComposerQueueProcessRoute:
    LovableCampaignComposerQueueProcessRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  ApiPublicAuthGoogleCallbackRoute: ApiPublicAuthGoogleCallbackRoute,
  ApiPublicAuthGoogleStartRoute: ApiPublicAuthGoogleStartRoute,
  ApiPublicAuthGoogleStatusRoute: ApiPublicAuthGoogleStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
